 ---
  - name: install sprut commerce
    become: yes
    hosts: all
    tasks:
    - name: Download nodejs file
      get_url:
        url: https://deb.nodesource.com/setup_14.x
        dest: /home/suresh/sprutcommerce
        mode: '1777'