---
  - name: install nop commerce
    become: yes
    hosts: all
    tasks:
      - name: download the debian file
        command:
          cmd: curl - SL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - name: Install nodejs
        command:
          cmd: sudo apt-get install -y nodejs