---
  - name: install nop commerce
    become: yes
    hosts: all
    tasks:
      - name: download the debian file
        get_url:
          url: https://deb.nodesource.com/setup_14.x
          dest: .
      - name: Install sprutcommerce
        apt:
          name: nodejs
          state: present
      - name: npm install
        npm:
          name: nodejs
          path: /app/location